Update patch set 2
Patch Set 2:

> Jim - FYI this hangs on my local mac.
 > Caused by: java.lang.NoClassDefFoundError: Could not initialize
 > class org.onap.policy.common.endpoints.http.server.YamlMessageBodyHandler
 > 
 > I just rebased common, models, re-compiled and api hangs.

Same issue on my local too. Maybe due to this class moved around in most recent change. i am fixing it.

Patch-set: 2