Update patch set 6
Patch Set 6:

> (2 comments)
 > 
 > > Build Failed
 > >
 > > https://jenkins.onap.org/job/policy-api-master-verify-java/9/ :
 > > FAILURE
 > >
 > > There are test failures. Please look in the log to identify them.
 > (
 > > https://jenkins.onap.org/job/policy-api-master-verify-java/9/ )
 > >
 > > Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/policy-api-master-verify-java/9
 > 
 > 13:39:30 [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0,
 > Time elapsed: 2.789 s <<< FAILURE! - in org.onap.policy.api.main.rest.TestApiRestServer
 > 13:39:30 [ERROR] testHealthCheckSuccess(org.onap.policy.api.main.rest.TestApiRestServer)
 >  Time elapsed: 0.26 s  <<< FAILURE!
 > 13:39:30 java.lang.AssertionError: expected:<true> but was:<false>
 > 13:39:30 	at org.onap.policy.api.main.rest.TestApiRestServer.validateReport(TestApiRestServer.java:112)
 > 13:39:30 	at org.onap.policy.api.main.rest.TestApiRestServer.testHealthCheckSuccess(TestApiRestServer.java:60)

I think root cause of this healthcheck status fail is in ApiActivator, the alive is not set to true during initialize() method. Instead it is set to true in terminate() method. 
In ApiActivator.initialize() , setAlive(true) 
In ApiActivator.terminate(), setAlive(false)

Patch-set: 6